### ISSUE TITLE
Doesn't appear to work with Photo Mode Camera

### ISSUE THREAD

**Issue by jrwillette** [TaleSpire-Modding/MaxDrawDistancePlugin#1]
This plugin is pretty awesome but I noticed it does not appear to work with the photo mode camera in TaleSpire.
It would be really amazing to have a separate setting for photomode and the normal camera.  That way one could keep the normal camera closer in, but really open up the photomode to get some amazing screenshots.

Thanks!

**Comment by brajm008** [comment]
Glad you are enjoying the plugin, I'll add that to my backlog and try and get that done when I get some time.
I'll also be adding some run-time configuration support with the configuration manager being WIP so you can eventually adjust the config on the fly with that installed.

**Comment by jrwillette** [comment]
Not sure if you updated the plugin or if it was the integration of the 2 different camera systems in TaleSpire, but it now appears that this works in both modes.  I don't feel the extra setting of having a further viewing distance in Photo mode is that important so I'm just going to mark this closed.
